"""add_multi_agent_development_tables

Revision ID: c3751fc92e5b
Revises: 0c02d1e20f60
Create Date: 2026-08-10 21:44:08.693303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3751fc92e5b'
down_revision: Union[str, Sequence[str], None] = '0c02d1e20f60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('development_agent_outputs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('version_id', sa.String(length=36), nullable=True),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('output_payload', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['development_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('development_artifacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('version_id', sa.String(length=36), nullable=True),
    sa.Column('artifact_type', sa.String(length=100), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('checksum', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['development_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('development_tasks',
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('version_id', sa.String(length=36), nullable=True),
    sa.Column('module', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_agent', sa.String(length=100), nullable=False),
    sa.Column('dependencies', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('requirement_id', sa.String(length=100), nullable=True),
    sa.Column('design_section_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['development_versions.id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.add_column('development_execution_logs', sa.Column('agent_name', sa.String(length=100), nullable=True))
    op.add_column('development_execution_logs', sa.Column('stage', sa.String(length=100), nullable=True))
    op.add_column('development_execution_logs', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('development_reviews', sa.Column('version_id', sa.String(length=36), nullable=True))
    op.add_column('development_reviews', sa.Column('rejected_modules', sa.Text(), nullable=True))
    op.add_column('development_reviews', sa.Column('quality_score', sa.Float(), nullable=True))
    op.add_column('development_reviews', sa.Column('security_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('development_reviews', 'security_score')
    op.drop_column('development_reviews', 'quality_score')
    op.drop_column('development_reviews', 'rejected_modules')
    op.drop_column('development_reviews', 'version_id')
    op.drop_column('development_execution_logs', 'error_message')
    op.drop_column('development_execution_logs', 'stage')
    op.drop_column('development_execution_logs', 'agent_name')
    op.drop_table('development_tasks')
    op.drop_table('development_artifacts')
    op.drop_table('development_agent_outputs')
    # ### end Alembic commands ###
