from typing import Dict, Any

class TemplateEngine:
    def __init__(self):
        self.templates: Dict[str, str] = {
            "fastapi_app": """import uvicorn
from fastapi import FastAPI, Depends, HTTPException, status
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

app = FastAPI(title="{title}", description="{description}", version="1.0.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get("/")
def read_root():
    return {{"status": "ok", "app": "{title}"}}
""",
            "sqlite_db": """import os
import sqlite3
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker, declarative_base

DATABASE_URL = os.getenv("DATABASE_URL", "sqlite:///./app_data.db")
engine = create_engine(DATABASE_URL, connect_args={{"check_same_thread": False}})
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()

def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
""",
            "html_entry": """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-slate-900 text-slate-100 min-h-screen flex flex-col justify-between">
    <header class="bg-slate-950 border-b border-slate-800 p-4">
        <h1 class="text-lg font-bold">{title}</h1>
    </header>
    <main class="flex-1 p-6 flex flex-col items-center justify-center">
        <div class="max-w-md w-full bg-slate-950/50 border border-slate-850 p-8 rounded-2xl shadow-xl">
            <h2 class="text-xl font-bold mb-4">Welcome to {title}</h2>
            <p class="text-xs text-slate-400 mb-6">{description}</p>
        </div>
    </main>
    <footer class="bg-slate-950 border-t border-slate-800 p-4 text-center text-[10px] text-slate-500">
        Generated by AI SDLC Studio
    </footer>
</body>
</html>
""",
            "readme_md": """# {title}

{description}

## Tech Stack
{tech_stack}

## Directory Structure
{directory_structure}

## Development Setup

1. Install dependencies:
```bash
pip install -r requirements.txt
```

2. Run the application:
```bash
uvicorn app.main:app --reload
```
"""
        }

    def render(self, name: str, context: Dict[str, Any]) -> str:
        template = self.templates.get(name, "")
        try:
            return template.format(**context)
        except Exception as e:
            print(f"Error rendering template '{name}': {e}")
            return template

template_engine = TemplateEngine()
